/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/common/app-provider.vue')['default']
    BaseLayout: typeof import('./../layout/base-layout/index.vue')['default']
    ButtonIcon: typeof import('./../components/custom/button-icon.vue')['default']
    CloseConfirm: typeof import('./../components/common/close-confirm.vue')['default']
    CollapseFooter: typeof import('./../layout/modules/global-footer/modules/collapse-footer.vue')['default']
    CollapseHeader: typeof import('./../layout/modules/global-header/modules/collapse-header.vue')['default']
    CollapseMenu: typeof import('./../layout/modules/global-menu/modules/collapse-menu.vue')['default']
    ExpendFooter: typeof import('./../layout/modules/global-footer/modules/expend-footer.vue')['default']
    ExpendHeader: typeof import('./../layout/modules/global-header/modules/expend-header.vue')['default']
    ExpendMenu: typeof import('./../layout/modules/global-menu/modules/expend-menu.vue')['default']
    GlobalFooter: typeof import('./../layout/modules/global-footer/index.vue')['default']
    GlobalHeader: typeof import('./../layout/modules/global-header/index.vue')['default']
    GlobalMenu: typeof import('./../layout/modules/global-menu/index.vue')['default']
    LoadingSpinner: typeof import('./../components/custom/loading-spinner.vue')['default']
    LoginDialog: typeof import('./../components/common/login-dialog.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NE: typeof import('naive-ui')['NE']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RightNavItemModal: typeof import('./../layout/modules/global-menu/modules/right-nav-item-modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
    UpdateConfirm: typeof import('./../components/common/update-confirm.vue')['default']
    WindowControls: typeof import('./../components/common/window-controls.vue')['default']
  }
}
